export const mockPosts = [
  {
    id: "1",
    title: "Modern Dashboard Design",
    description: "A clean and intuitive dashboard interface for a SaaS platform with dark mode support.",
    image: "/placeholder.svg?height=400&width=400&text=Dashboard Design",
    author: {
      name: "Sarah Chen",
      title: "UI/UX Designer",
      avatar: "/placeholder.svg?height=40&width=40&text=SC",
    },
    likes: 234,
    comments: 18,
    tags: ["UI Design", "Dashboard", "Dark Mode"],
  },
  {
    id: "2",
    title: "Brand Identity for Coffee Shop",
    description: "Complete brand identity design including logo, packaging, and storefront design.",
    image: "/placeholder.svg?height=400&width=400&text=Coffee Brand",
    author: {
      name: "Marcus Johnson",
      title: "Brand Designer",
      avatar: "/placeholder.svg?height=40&width=40&text=MJ",
    },
    likes: 189,
    comments: 12,
    tags: ["Branding", "Logo Design", "Packaging"],
  },
  {
    id: "3",
    title: "Mobile App Wireframes",
    description: "Low-fidelity wireframes for a fitness tracking mobile application.",
    image: "/placeholder.svg?height=400&width=400&text=Mobile Wireframes",
    author: {
      name: "Emily Rodriguez",
      title: "UX Designer",
      avatar: "/placeholder.svg?height=40&width=40&text=ER",
    },
    likes: 156,
    comments: 24,
    tags: ["Mobile Design", "Wireframes", "UX"],
  },
  {
    id: "4",
    title: "3D Product Visualization",
    description: "Photorealistic 3D renders of consumer electronics for marketing materials.",
    image: "/placeholder.svg?height=400&width=400&text=3D Product",
    author: {
      name: "David Kim",
      title: "3D Artist",
      avatar: "/placeholder.svg?height=40&width=40&text=DK",
    },
    likes: 298,
    comments: 31,
    tags: ["3D Modeling", "Product Design", "Visualization"],
  },
  {
    id: "5",
    title: "Website Redesign Concept",
    description: "Modern redesign concept for an e-commerce website with improved user experience.",
    image: "/placeholder.svg?height=400&width=400&text=Website Redesign",
    author: {
      name: "Lisa Wang",
      title: "Web Designer",
      avatar: "/placeholder.svg?height=40&width=40&text=LW",
    },
    likes: 167,
    comments: 19,
    tags: ["Web Design", "E-commerce", "UX"],
  },
  {
    id: "6",
    title: "Illustration Series",
    description: "A series of digital illustrations exploring themes of nature and technology.",
    image: "/placeholder.svg?height=400&width=400&text=Illustration",
    author: {
      name: "Alex Rivera",
      title: "Illustrator",
      avatar: "/placeholder.svg?height=40&width=40&text=AR",
    },
    likes: 445,
    comments: 52,
    tags: ["Illustration", "Digital Art", "Nature"],
  },
]
export const mockJobs = [
  {
    id: "1",
    title: "Senior UI/UX Designer",
    company: "TechFlow Inc.",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: 120000,
    description:
      "We're looking for a senior UI/UX designer to join our product team and help shape the future of our SaaS platform.",
    skills: ["Figma", "Sketch", "Prototyping", "User Research", "Design Systems"],
    postedDate: "2024-01-15",
  },
  {
    id: "2",
    title: "Freelance Brand Designer",
    company: "Creative Studio Co.",
    location: "Remote",
    type: "Freelance",
    salary: 75000,
    description:
      "Seeking a talented brand designer for a 3-month project to develop a complete brand identity for a startup.",
    skills: ["Brand Design", "Logo Design", "Adobe Creative Suite", "Typography"],
    postedDate: "2024-01-14",
  },
  {
    id: "3",
    title: "Frontend Developer",
    company: "Digital Innovations",
    location: "New York, NY",
    type: "Full-time",
    salary: 95000,
    description: "Join our development team to build beautiful, responsive web applications using modern technologies.",
    skills: ["React", "TypeScript", "CSS", "JavaScript", "Next.js"],
    postedDate: "2024-01-13",
  },
  {
    id: "4",
    title: "Motion Graphics Designer",
    company: "Media Works",
    location: "Los Angeles, CA",
    type: "Contract",
    salary: 85000,
    description: "Create engaging motion graphics and animations for various digital marketing campaigns.",
    skills: ["After Effects", "Cinema 4D", "Motion Design", "Animation"],
    postedDate: "2024-01-12",
  },
  {
    id: "5",
    title: "Product Designer",
    company: "StartupXYZ",
    location: "Austin, TX",
    type: "Full-time",
    salary: 110000,
    description:
      "Lead the design of our mobile app from concept to launch, working closely with product and engineering teams.",
    skills: ["Product Design", "Mobile Design", "User Testing", "Figma"],
    postedDate: "2024-01-11",
  },
]
export const mockUsers = [
  {
    id: "1",
    name: "Sarah Chen",
    title: "UI/UX Designer",
    location: "San Francisco, CA",
    avatar: "/placeholder.svg?height=80&width=80&text=SC",
    followers: 1234,
    projects: 45,
    skills: ["UI Design", "UX Research", "Figma", "Prototyping"],
  },
  {
    id: "2",
    name: "Marcus Johnson",
    title: "Brand Designer",
    location: "New York, NY",
    avatar: "/placeholder.svg?height=80&width=80&text=MJ",
    followers: 892,
    projects: 32,
    skills: ["Branding", "Logo Design", "Typography", "Packaging"],
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    title: "UX Designer",
    location: "Chicago, IL",
    avatar: "/placeholder.svg?height=80&width=80&text=ER",
    followers: 567,
    projects: 28,
    skills: ["UX Research", "Wireframing", "User Testing", "Information Architecture"],
  },
  {
    id: "4",
    name: "David Kim",
    title: "3D Artist",
    location: "Seattle, WA",
    avatar: "/placeholder.svg?height=80&width=80&text=DK",
    followers: 2103,
    projects: 67,
    skills: ["3D Modeling", "Blender", "Cinema 4D", "Product Visualization"],
  },
  {
    id: "5",
    name: "Lisa Wang",
    title: "Web Designer",
    location: "Portland, OR",
    avatar: "/placeholder.svg?height=80&width=80&text=LW",
    followers: 743,
    projects: 39,
    skills: ["Web Design", "Frontend Development", "Responsive Design", "CSS"],
  },
  {
    id: "6",
    name: "Alex Rivera",
    title: "Illustrator",
    location: "Miami, FL",
    avatar: "/placeholder.svg?height=80&width=80&text=AR",
    followers: 1567,
    projects: 52,
    skills: ["Digital Illustration", "Character Design", "Concept Art", "Adobe Illustrator"],
  },
]
export const mockProjects = [
  {
    id: "1",
    title: "E-commerce Mobile App",
    description: "Complete mobile app design for a fashion e-commerce platform with AR try-on features.",
    image: "/placeholder.svg?height=300&width=400&text=Mobile App",
    technologies: ["Figma", "Prototyping", "User Research"],
    year: "2024",
  },
  {
    id: "2",
    title: "SaaS Dashboard Redesign",
    description: "Comprehensive redesign of a complex analytics dashboard with improved data visualization.",
    image: "/placeholder.svg?height=300&width=400&text=Dashboard",
    technologies: ["UI Design", "Data Visualization", "Design System"],
    year: "2023",
  },
  {
    id: "3",
    title: "Brand Identity System",
    description:
      "Complete brand identity for a sustainable fashion startup including logo, guidelines, and applications.",
    image: "/placeholder.svg?height=300&width=400&text=Brand Identity",
    technologies: ["Brand Design", "Logo Design", "Guidelines"],
    year: "2023",
  },
  {
    id: "4",
    title: "Website Redesign",
    description: "Modern website redesign for a tech consultancy with focus on conversion optimization.",
    image: "/placeholder.svg?height=300&width=400&text=Website",
    technologies: ["Web Design", "UX Optimization", "Responsive Design"],
    year: "2024",
  },
  {
    id: "5",
    title: "Mobile Game UI",
    description: "User interface design for a casual mobile puzzle game with engaging animations.",
    image: "/placeholder.svg?height=300&width=400&text=Game UI",
    technologies: ["Game UI", "Mobile Design", "Animation"],
    year: "2023",
  },
  {
    id: "6",
    title: "Design System",
    description: "Comprehensive design system for a fintech company with 50+ components and guidelines.",
    image: "/placeholder.svg?height=300&width=400&text=Design System",
    technologies: ["Design Systems", "Component Library", "Documentation"],
    year: "2024",
  },
]
export const mockResources = [
  {
    id: "1",
    title: "Design System Best Practices",
    description: "A comprehensive guide to building and maintaining scalable design systems for modern products.",
    category: "Guide",
  },
  {
    id: "2",
    title: "Color Theory for Designers",
    description: "Master the fundamentals of color theory and learn how to create harmonious color palettes.",
    category: "Tutorial",
  },
  {
    id: "3",
    title: "Figma Component Library",
    description: "A collection of reusable UI components and templates to speed up your design workflow.",
    category: "Resource",
  },
  {
    id: "4",
    title: "UX Research Methods",
    description: "Learn about different UX research methods and when to use each one in your design process.",
    category: "Guide",
  },
  {
    id: "5",
    title: "Typography Guidelines",
    description: "Essential typography principles and guidelines for creating readable and beautiful text layouts.",
    category: "Reference",
  },
  {
    id: "6",
    title: "Mobile Design Patterns",
    description: "Common mobile design patterns and best practices for creating intuitive mobile experiences.",
    category: "Resource",
  },
]